[package]
name = "voxel-raymarcher-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
glam = "0.27.0"
lazy_static = "1.4.0"
noise = "0.9.0"
rand = "0.8.5"
raylib = "5.0.1"
